namespace Domain.Models.Database;
public enum ApplicationPage
{
    ApplicationCode = 1,
    CQCProviderID,
    CQCProviderConfirmation,
    CQCProviderNotFound,
    CQCProviderHasActiveLicence,
    CQCProviderChange,
    CQCProviderChangeName,
    CQCProviderChangeAddress,
    CQCProviderChangePhoneNumber,
    CQCProviderChangeWebsite,
    CompanyNumberCheck,
    CompanyNumber,
    NewlyIncorporatedCompany,
    LastFinancialYear,
    NextFinancialYear,
    DirectorCheck,
    Directors,
    CorporateDirectorCheck,
    CorporateBodies,
    CorporateBodyName,
    CorporateBodyIndividualsOrCompany,
    CorporateDirectors,
    ParentCompaniesCheck,
    ParentCompanies,
    ParentCompanyName,
    ParentCompanyDirectorsOrEquivalents,
    ParentCompanyDirectors,
    DirectorsSatisfyG3FitAndProperRequirements,
    UltimateController,
    UltimateControllers,
    Review,
    Submitted
}
